#Configuration#
Plugin:
#AutoUpdate the plugin when a update is found#
  AutoUpdate: true
  #Debug Mode#
  Debug: false
#Reasons not to add special equipmemt#
#If true blocks usage#
Reason:
  Spawner: true
  Egg: true
DropFix:
  #Adds Damage to drops#
  Damage: true
#When adding enchantments, only allow safe or item specific enchantments#
SafeEnchant:
  Enabled: false
#Allow the drop of custom items (custom.yml)#
Custom:
  #Overtake all random items#
  Only: false
  Enabled: true
  Chance: 1
#Allow the drop of lore items (lore.txt enhancements)#
Lore:
  Enabled: true
  Chance: 5
  EnhanceAmount: 1
#Changing the way that a few things are displayed#
Display:
  TierName: true
  ColorBlind: false
  ItemMaterialExtras: false
  ItemNameFormat: '%randprefix% %randsuffix%'
#Allow the drop of book to "identify" Magic color items#
IdentifyTome:
  Enabled: true
  Chance: 2
  
##Disabled 2.6
#SockettedItem:
#  Enabled: true
#  Chance: 20
#  MinimumSockets: 1
#  MaximumSockets: 5

#Allow the drop of socket items#
#SocketItem:
#  Enabled: true
#  Chance: 5
#  #Whether to set lore on sockets#
#  Lore: true
#  Items: 
#  - Emerald
#  - Diamond
#  - Skull_Item

Colors:
- GREEN
- RED
- BLUE

#This is the initial chance an enemy will spawn with an item#
Percentages:
  ChancePerSpawn: 3
  
#Specific Worlds#
Worlds:
  Enabled: false
  #Enable Specific Worlds
  Allowed:
  - 'world'
  - 'world_nether'
  - 'world_the_end'
